security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers

    encoders:
        App\Entity\Account\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: App\Entity\Account\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
